.TH "gtping" "8" "8th May, 2009" "gtping" ""

.PP 
.SH "NAME"
gtping \- sends GTP pings to a GSN
.PP 
.SH "SYNOPSIS"
\fBgtping\fP [ -\fBhvV\fP ] [ -\fBc\fP \fIcount\fP ] [ -\fBp\fP \fIport\fP ] [ -\fBt\fP \fIteid\fP ] [ -\fBT\fP \fIttl\fP ] [ -\fBw\fP \fItime\fP ] \fIdestination\fP
.PP 
.SH "DESCRIPTION"
\fBgtping\fP sends GTP Echo requests to GSNs (such as GGSN), and  requests
to the specified \fIhost\fP and displays the replies similarly to \fBping\fP
on most systems (\fBping -s\fP on Solaris)\&.
.PP 
By default one request is sent each second\&. This can be changed with
\fB-w\fP\&.
.PP 
.SH "OPTIONS"

.IP 
.IP "-c \fIcount\fP"
Stop after sending \fIcount\fP pings\&. Default is 0 which
means continue until user presses Ctrl-C\&.
.IP "-h, --help"
Show brief usage info and exit\&.
.IP "-V, --version"
Show version and exit\&.
.IP "-p \fIport\fP"
Destination UDP port to use\&. Default is 2123\&.
.IP "-t \fIteid\fP"
Transaction ID to use\&. Default is 0\&.
.IP "-T \fIttl\fP"
TTL of IP packet\&. Default is to use system default\&.
.IP "-w \fItime\fP"
Time in seconds between sending pings\&. Default is 1\&.
Fractional seconds are supported, for example \fB-w 0\&.1\fP will send one
ping every 100ms\&.

.PP 
.SH "Example"
.nf
.sp
$ \&./gtping -c 1 1\&.2\&.3\&.4
GTPing 0\&.13, By Thomas Habets <thomas@habets\&.pp\&.se>
GTPING 1\&.2\&.3\&.4 (1\&.2\&.3\&.4) 12 bytes of data\&.
12 bytes from 1\&.2\&.3\&.4: seq=0 time=0\&.51 ms
.PP 
--- 1\&.2\&.3\&.4 GTP ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 1000ms
0 out of order, 0 dups, 0 ICMP error, 0 connection refused
rtt min/avg/max/mdev = 0\&.512/0\&.512/0\&.512/0\&.000 ms
.fi
.in
.PP 
.SH "BUGS"
No known bugs\&.
.PP 
.SH "SEE ALSO"

.PP 
\fBping(8)\fP, \fBarping(8)\fP
.PP 
.SH "AUTHOR"
GTPing was written by Thomas Habets <thomas@habets\&.pp\&.se>\&.
.PP 
